# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "274e0a5993dca0a720172693c7a0b7d0"
name = "VEND"
application_url = "http://localhost:8000"
embedded = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = ["http://localhost:8000/callback/shopify"]
